import Head from "next/head";
import Link from "next/link";
import styled, { keyframes } from "styled-components";

import Header from "../components/header";
import Footer from "../components/footer";

const pages = [
  {
    id: 1,
    href: "/logo",
    text: "Logo Animation",
  },
  {
    id: 2,
    href: "/search",
    text: "Search",
  },
];

export default function Home() {
  const PageLinks = pages.map((page, idx) => {
    const style = { "--delay": (idx + 1) * 20 + 500 + "ms" };

    return (
      <ListItem key={page.id} style={style}>
        <Link href={page.href}>
          <a>{page.text}</a>
        </Link>
      </ListItem>
    );
  });

  return (
    <>
      <Head>
        <title>Animations</title>
        <meta name="description" content="Generated by Animations" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteWrapper>
        <Header />
        <MainWrapper>
          <HeaderWrapper>
            <h1>Welcome to my Animation showcase</h1>
            <p>
              I have prepared a few demos, feel free to pick any of them to see
              it
            </p>

            <List>{PageLinks}</List>
          </HeaderWrapper>
        </MainWrapper>
        <Footer />
      </SiteWrapper>
    </>
  );
}

const fadeIn = keyframes`
  0% {
    opacity: 0;
    transform: scale(0.8);
  }

  100% {
    opacity: 1;
    transform: scale(1);
  }
`;

const HeaderWrapper = styled.header`
  text-align: center;
  padding: 0 var(--mobile-gutter);

  h1 {
    margin: 0;
    font-size: clamp(2em, 5vw, 5em);

    animation: ${fadeIn} 1s ease-in-out 0s;
    animation-fill-mode: both;
  }

  p {
    margin: 1em 0 0 0;
    font-size: 1.25em;

    animation: ${fadeIn} 0.75s ease-in-out 0.25s;
    animation-fill-mode: both;
  }
`;

const MainWrapper = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: center;
`;

const SiteWrapper = styled.div`
  display: grid;
  grid-template-rows: auto 1fr auto;
  width: 100%;
  height: 100%;

  h1 {
    letter-spacing: -0.01em;
    font-size: 3em;
  }

  p {
    font-family: var(--font-secondary);
  }
`;

const List = styled.ul`
  margin: 2em;
  padding: 0;
  list-style-type: none;
  gap: 1em;
  display: flex;
  justify-content: center;
`;

const ListItem = styled.li`
  a {
    display: inline-block;
    padding: 0.5em 1em;
    border-radius: 0.5em;
    border: 2px solid #ddd;
    font-weight: 500;
    transition: 0.2s;
    animation: ${fadeIn} 0.5s ease-in-out 2s;
    animation-delay: var(--delay);
    animation-fill-mode: both;

    &:hover {
      transition: 0.2s;
      border-color: red;
      color: red;
      transform: scale(1.05);
    }

    &:active {
      transition: 0.2s;
      transform: scale(0.9);
    }
  }
`;
