import Head from "next/head";
import styled from "styled-components";

import Header from "../components/header";
import Footer from "../components/footer";

const SiteWrapper = styled.div`
  display: grid;
  grid-template-rows: auto 1fr auto;
  width: 100%;
  height: 100%;

  h1 {
    font-family: ShadowsIntoLight;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteWrapper>
        <Header />
        <main>
          <header>
            <h1>Welcome to my Animation showcase</h1>
            <p>
              I have prepared a few demos, feel free to pick any of them to see
              it
            </p>
          </header>
        </main>
        <Footer />
      </SiteWrapper>
    </>
  );
}
