import Head from "next/head";
import styled, { keyframes } from "styled-components";

import Header from "../components/header";
import Footer from "../components/footer";

import { Main } from '../components/layout/main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <Header />

        <Main>
          <p>Hello world</p>
        </Main>

        <Footer />
    </>
  );
}

const showHeadline = keyframes`
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
`;
