import Head from "next/head";
import { useState } from "react";
import styled, { keyframes, css } from "styled-components";

import Header from "../components/header";
import Footer from "../components/footer";
import Explanation from "../components/explanation";

import { Main } from "../components/layout/main";

const AnswerItem = ({ children, delay }) => {
  const [clicked, setClicked] = useState(false);

  return (
    <Answer
      delay={delay}
      clicked={clicked}
      onClick={() => setClicked(!clicked)}
    >
      <Checkbox />
      <span>{children}</span>
    </Answer>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Animations</title>
        <meta name="description" content="Generated by Animations" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main maxWidth={30}>
        <h1>Quiz animation</h1>

        <QuizWrapper>
          <Question>
            Which car manufacturer was the first to offer air conditioning?
          </Question>
          <Answers>
            <AnswerItem delay={200}>Toyota</AnswerItem>
            <AnswerItem delay={300}>Packard</AnswerItem>
            <AnswerItem delay={400}>BMW</AnswerItem>
            <AnswerItem delay={500}>Audi</AnswerItem>
          </Answers>
        </QuizWrapper>

        <Explanation>
          <p>Quiz.</p>
        </Explanation>
      </Main>

      <Footer />
    </>
  );
}

const showBox = keyframes`
  0% {
    opacity: .7;
    transform: scale(.98) translateZ(-1em);
  }
  100% {
    opacity: 1;
    transform: scale(1) translateY(0);
  }
`;

const showCheckbox = keyframes`
  0% {
    opacity: 0;
    transform: translateX(-.5em);
  }
  100% {
    opacity: 1;
    transform: translateX(0);
  }
`;

const QuizWrapper = styled.div`
  --shadow-color: 0deg 0% 50%;

  transform-origin: bottom center;
  animation-name: ${showBox};
  animation-duration: 1s;
  animation-fill-mode: both;
  background: #9b1cff;
  padding: 2.5em;
  border-radius: 1em;
  box-shadow: 1px 2px 2px hsl(var(--shadow-color) / 0.2),
    2px 4px 4px hsl(var(--shadow-color) / 0.2),
    4px 8px 8px hsl(var(--shadow-color) / 0.2),
    8px 16px 16px hsl(var(--shadow-color) / 0.2),
    16px 32px 32px hsl(var(--shadow-color) / 0.2);
`;

const Question = styled.div`
  font-size: 2.5em;
  font-weight: 900;
  background: -webkit-linear-gradient(43deg, #ffffff 0%, #bab3ff 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
`;

const Checkbox = styled.span`
  width: 1.5em;
  height: 1.5em;
  border: 4px solid #7b71e0;
  border-radius: 0.25em;
  animation-name: ${showCheckbox};
  animation-duration: 1s;
  animation-fill-mode: both;
`;

const Answer = styled.li`
  --shadow-color: 0deg 0% 50%;

  padding: 1.5em;
  border-radius: 0.5em;
  box-shadow: 1px 2px 2px hsl(var(--shadow-color) / 0.1),
    2px 4px 4px hsl(var(--shadow-color) / 0.1),
    3px 6px 6px hsl(var(--shadow-color) / 0.1);

  font-weight: 500;
  background: white;
  margin: 0.5em 0;
  cursor: pointer;
  display: flex;
  gap: 0.5em;
  align-items: center;
  transition: 0.2s;
  opacity: 0.95;
  animation-delay: ${(props) => props.delay + "ms"};

  ${Checkbox} {
    animation-delay: ${(props) => props.delay + "ms"};
  }

  span {
    animation-name: ${showCheckbox};
    animation-duration: 1s;
    animation-fill-mode: both;
    animation-delay: ${(props) => props.delay + 200 + "ms"};
  }

  &:hover {
    transform: scale(1.01);
    transition: 0.2s;
    opacity: 1;
  }

  &:active {
    transform: scale(0.97);
    transition: 0.05s;
    opacity: 1;
  }

  ${({ clicked }) =>
    clicked &&
    css`
      opacity: 1;

      ${Checkbox} {
        background-color: #7b71e0;
        background-repeat: no-repeat;
        background-position: center center;
        background-size: 70% 70%;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='%23fff' d='M10 15.172l9.192-9.193 1.415 1.414L10 18l-6.364-6.364 1.414-1.414z'/%3E%3C/svg%3E");
      }
    `}
`;

const Answers = styled.ul`
  margin-top: 2em;
  margin-bottom: 0;
  padding: 0;
  list-style-type: none;
  transition: 0.2s;

  &:hover ${Answer} {
    opacity: 0.97;
    transition: 0.2s;
  }
`;
